[project]
name = "langgraph-foundation-academy-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.4",
    "cryptography>=46.0.7",
    "ipykernel>=7.2.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.28",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.1.14",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.1.9",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "langgraph-cli[inmem]>=0.4.24",
    "langgraph-prebuilt>=1.0.10",
    "langgraph-sdk>=0.3.13",
    "langsmith>=0.7.31",
    "notebook>=7.5.5",
    "pygments>=2.20.0",
    "trustcall>=0.0.39",
    "wikipedia>=1.4.0",
]
